### ISSUE TITLE
fix spec tests under puppet 4: fqdn_rand() has enlarged the entropy pool

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-mcollective#294]
#290 is seeing the first set of failures caused by https://docs.puppetlabs.com/puppet/4.4/reference/release_notes.html#puppet-440 / https://tickets.puppetlabs.com/browse/PUP-5646

Perhaps we should rethink… or generalise… how these tests of the cron resource ought to look like. so that they can work under puppet 3 as well as puppet 4.

**Comment by daenney** [comment]
I think the issue here is that we're testing for the output of `fqdn_rand`. By virtue of what it does this is supposed to be unpredictable, hence the tests are actually broken.

The only thing we really care about is that it produces an X amount of expected values, not the exact value of those values. The check should just see if it's an array of 4 values.

**Comment by petems** [comment]
Well, we need to check that it produces 4 values that aren't 0, 15, 30, 45, as otherwise they're not being randomised.

I think the reason I did just check the values weren't 0, 15, 30 and 45, was having issues checking values weren't those given values with this code:

```
context 'true' do
  let(:params) { { fact_cron_splay: true } }
  it { should contain_cron('refresh-mcollective-metadata').without_minute(%w(0 15 30 45)) }
end
```

Looking back on it now, that should really be:
```ruby
context 'true' do
  let(:params) { { fact_cron_splay: true } }
  it { should_not contain_cron('refresh-mcollective-metadata').with_minute(%w(0 15 30 45)) }
  it { should contain_cron('refresh-mcollective-metadata') }
end
```

I'd like it to match the `anything()` mocha argument, but that doesn't seem to work with rspec-puppet:

```
1) mcollective installing a server #factsource yaml_facter2 #fact_cron_splay true should contain Cron[refresh-mcollective-metadata] with minute => #<Mocha::ParameterMatchers::Anything:0x007fb60c9dde28>
     Failure/Error: it { should contain_cron('refresh-mcollective-metadata').with_minute(anything()) }

       expected that the catalogue would contain Cron[refresh-mcollective-metadata] with minute set to #<Mocha::ParameterMatchers::Anything:0x007fb60c9dde28> but it is set to [7, 22, 37, 52]
       Diff:
       @@ -1,2 +1,8 @@
       -#<Mocha::ParameterMatchers::Anything:0x007fb60c9dde28>
       +7
       +
       +22
       +
       +37
       +
       +52
```

I've opened an issue for that anyways (https://github.com/rodjek/rspec-puppet/issues/380), in the mean time I'll simplfiy the tests to make sure it's not the defaults

**Comment by petems** [comment]
https://github.com/voxpupuli/puppet-mcollective/pull/295
